module.exports = {
  rules: {
    'color-no-invalid-hex': true,
    'font-family-no-duplicate-names': true,
    'font-family-no-missing-generic-family-keyword': true,
    'named-grid-areas-no-invalid': true,
    'function-calc-no-unspaced-operator': true,
    'function-linear-gradient-no-nonstandard-direction': true,
    'string-no-newline': true,
    'unit-no-unknown': true,
    'property-no-unknown': true,
    'keyframe-declaration-no-important': true,
    'declaration-block-no-duplicate-properties': [
      true,
      {
        ignore: [
          'consecutive-duplicates-with-different-values',
        ],
      },
    ],
    'declaration-block-no-shorthand-property-overrides': true,
    'block-no-empty': true,
    'selector-pseudo-class-no-unknown': true,
    'selector-type-no-unknown': true,
    'media-feature-name-no-unknown': true,
    'comment-no-empty': true,
    'no-duplicate-at-import-rules': true,
    'no-duplicate-selectors': true,
    'alpha-value-notation': 'number',
    'hue-degree-notation': 'angle',
    'font-weight-notation': null,
    'function-url-no-scheme-relative': true,
    'shorthand-property-no-redundant-values': true,
    'value-no-vendor-prefix': true,
    'declaration-no-important': true,
    'declaration-block-single-line-max-declarations': 1,
    'color-hex-length': 'short',
    'font-family-name-quotes': 'always-unless-keyword',
    'function-name-case': 'lower',
    'comment-empty-line-before': [
      'always',
      {
        except: [
          'first-nested',
        ],
        ignore: [
          'stylelint-commands',
        ],
      },
    ],
    'comment-whitespace-inside': 'always',
    'length-zero-no-unit': true,
    'selector-class-pattern': null,
    'custom-property-pattern': null,
    'at-rule-empty-line-before': null,
    'declaration-empty-line-before': null,
    'rule-empty-line-before': null,
    'declaration-block-no-redundant-longhand-properties': null,
    'color-function-notation': 'legacy',
    'declaration-property-value-no-unknown': true,
  },
};
