name: test and lint
on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        check-latest: true
        node-version: 22

    - run: yarn install
    - run: yarn run lint:all
    - run: yarn run build:all
    - run: yarn run test:all
