name: test and lint
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        check-latest: true
        node-version: 16
    - run: npm i
    - run: yarn run lint:all
    - run: yarn run test:all
    - run: yarn run build:all
